import wikipedia

amy_klobuchar = wikipedia.page(title='Amy Klobuchar')
andrew_yang = wikipedia.page(title='Andrew Yang 2020 presidential campaign')
arvin_vohra = wikipedia.page(title='Arvin Vohra')
bernie_sanders = wikipedia.page(title='Political positions of Bernie Sanders')
beto_orourke = wikipedia.page(title="Beto O'Rourke")
bill_weld = wikipedia.page(title='Bill Weld 2020 presidential campaign')
cory_booker = wikipedia.page(title='Political positions of Cory Booker')
donald_trump = wikipedia.page(title='Political positions of Donald Trump')
elizabeth_warren = wikipedia.page(title='Political positions of Elizabeth Warren')
eric_swalwell = wikipedia.page(title='Eric Swalwell')
howard_shultz = wikipedia.page(title='Howard Shultz')
jay_inslee = wikipedia.page(title='Jay Inslee 2020 presidential campaign')
jesse_ventura = wikipedia.page(title='Jesse Ventura')
joe_biden = wikipedia.page(title='Political positions of Joe Biden')
john_delaney = wikipedia.page(title='Political positions of John Delaney')
john_hickenlooper = wikipedia.page(title='John Hickenlooper')
john_kasich = wikipedia.page(title='John Kasich')
julian_castro = wikipedia.page(title='Julian Castro')
kamala_harris = wikipedia.page(title='Kamala Harris')
kirsten_gillibrand = wikipedia.page(title='Political positions of Kirsten Gillibrand')
larry_hogan = wikipedia.page(title='Larry Hogan')
marianne_williamson = wikipedia.page(title='Marianne Williamson')
michael_bennet = wikipedia.page(title='Michael Bennet')
mike_gravel = wikipedia.page(title='Mike Gravel')
mike_pence = wikipedia.page(title='Mike Pence')
pete_buttigieg = wikipedia.page('Pete Buttigieg 2020 presidential campaign')
tulsi_gabbard = wikipedia.page(title='Tulsi Gabbard')
tim_ryan = wikipedia.page(title='Tim Ryan (Ohio politician)')
